/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLineMdUploadingLoop: typeof import('~icons/line-md/uploading-loop.svelte')['default']
  const IconMapPin: (typeof import('~icons/map/pin.svelte'))['default']
  const IconPhBriefcase: typeof import('~icons/ph/briefcase.svelte')['default']
  const IconPhCalendar: typeof import('~icons/ph/calendar.svelte')['default']
  const IconPhCalendarDots: typeof import('~icons/ph/calendar-dots.svelte')['default']
  const IconPhCameraPlus: typeof import('~icons/ph/camera-plus.svelte')['default']
  const IconPhCaretLeft: typeof import('~icons/ph/caret-left.svelte')['default']
  const IconPhCaretLeftLight: (typeof import('~icons/ph/caret-left-light.svelte'))['default']
  const IconPhCaretRight: typeof import('~icons/ph/caret-right.svelte')['default']
  const IconPhExclamationMarkFill: (typeof import('~icons/ph/exclamation-mark-fill.svelte'))['default']
  const IconPhHeart: typeof import('~icons/ph/heart.svelte')['default']
  const IconPhHeartFill: typeof import('~icons/ph/heart-fill.svelte')['default']
  const IconPhMapPinLine: typeof import('~icons/ph/map-pin-line.svelte')['default']
  const IconPhNotePencil: typeof import('~icons/ph/note-pencil.svelte')['default']
  const IconPhPlusSquare: typeof import('~icons/ph/plus-square.svelte')['default']
  const IconPhTrash: typeof import('~icons/ph/trash.svelte')['default']
  const IconPhUserCircleGear: typeof import('~icons/ph/user-circle-gear.svelte')['default']
  const IconPhUsers: typeof import('~icons/ph/users.svelte')['default']
  const IconPhUsersFour: typeof import('~icons/ph/users-four.svelte')['default']
  const IconPhX: typeof import('~icons/ph/x.svelte')['default']
  const IconPhXCircle: (typeof import('~icons/ph/x-circle.svelte'))['default']
  const IconTablerBuildingEstate: typeof import('~icons/tabler/building-estate.svelte')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.svelte')['default']
  const IconTablerTag: (typeof import('~icons/tabler/tag.svelte'))['default']
}
