import Config

# For staging, we use mostly the same config as prod
# but with some adjustments for easier debugging

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tempi, TempiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client (keeping same as prod)
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Tempi.Finch

# Disable Swoosh Local Memory Storage (keeping same as prod)
config :swoosh, local: false

# Use info level logging for staging (same as prod)
config :logger, level: :info

# Runtime staging configuration, including reading
# of environment variables, is done on config/runtime.exs.
