/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLineMdLoadingTwotoneLoop: typeof import('~icons/line-md/loading-twotone-loop.svelte')['default']
  const IconPhBriefcase: typeof import('~icons/ph/briefcase.svelte')['default']
  const IconPhCalendar: typeof import('~icons/ph/calendar.svelte')['default']
  const IconPhCalendarDots: typeof import('~icons/ph/calendar-dots.svelte')['default']
  const IconPhCaretLeft: typeof import('~icons/ph/caret-left.svelte')['default']
  const IconPhCaretRight: typeof import('~icons/ph/caret-right.svelte')['default']
  const IconPhClipboardText: typeof import('~icons/ph/clipboard-text.svelte')['default']
  const IconPhMapPinLine: typeof import('~icons/ph/map-pin-line.svelte')['default']
  const IconPhPlusBold: typeof import('~icons/ph/plus-bold.svelte')['default']
  const IconPhUserCircleGear: typeof import('~icons/ph/user-circle-gear.svelte')['default']
  const IconPhUsers: typeof import('~icons/ph/users.svelte')['default']
  const IconPhUsersFour: typeof import('~icons/ph/users-four.svelte')['default']
  const IconPhX: typeof import('~icons/ph/x.svelte')['default']
  const IconTablerBriefcase: typeof import('~icons/tabler/briefcase.svelte')['default']
  const IconTablerBuildingEstate: typeof import('~icons/tabler/building-estate.svelte')['default']
  const IconTablerCalendar: typeof import('~icons/tabler/calendar.svelte')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.svelte')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.svelte')['default']
  const IconTablerClock: typeof import('~icons/tabler/clock.svelte')['default']
  const IconTablerCurrencyShekel: typeof import('~icons/tabler/currency-shekel.svelte')['default']
  const IconTablerDotsVertical: typeof import('~icons/tabler/dots-vertical.svelte')['default']
  const IconTablerHeart: typeof import('~icons/tabler/heart.svelte')['default']
  const IconTablerMapPin: typeof import('~icons/tabler/map-pin.svelte')['default']
  const IconTablerUpload: typeof import('~icons/tabler/upload.svelte')['default']
  const IconTablerUser: typeof import('~icons/tabler/user.svelte')['default']
  const IconTablerUsers: typeof import('~icons/tabler/users.svelte')['default']
}
