/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconPhCalendarDots: typeof import('~icons/ph/calendar-dots.svelte')['default']
  const IconPhCaretLeft: typeof import('~icons/ph/caret-left.svelte')['default']
  const IconPhCaretRight: typeof import('~icons/ph/caret-right.svelte')['default']
  const IconTablerHexagonPlusFilled: typeof import('~icons/tabler/hexagon-plus-filled.svelte')['default']
  const PhCaretLeft: (typeof import('~icons/ph/caret-left.svelte'))['default']
  const PhCaretRight: (typeof import('~icons/ph/caret-right.svelte'))['default']
  const element: (typeof import('~icons/el/ement.svelte'))['default']
  const lang: (typeof import('~icons/la/ng.svelte'))['default']
  const window: (typeof import('~icons/wi/ndow.svelte'))['default']
}
